<?xml version="1.0"?>
<robot name="plen2" xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <!-- Gazebo Simulation Plugins -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/plen2</robotNamespace>
            <controlPeriod>0.001</controlPeriod>
        </plugin>
    </gazebo>
    
    <!-- Base Link -->
    <link name="base_link">
        <inertial>
            <mass value="1.5"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
        </inertial>
        <visual>
            <geometry>
                <mesh filename="package://plen2_description/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="0.1 0.1 0.05"/>
            </geometry>
        </collision>
    </link>
    
    <!-- Physics Settings -->
    <gazebo reference="base_link">
        <mu1>0.5</mu1>
        <mu2>0.5</mu2>
        <kp>100000.0</kp>
        <kd>10.0</kd>
    </gazebo>
</robot>

